### ISSUE TITLE
Feature request : utility tag sanitization method

### ISSUE THREAD

**Issue by mgravell** [bretcope/BosunReporter.NET#16]
Not all tag values are valid; the library includes features to *check* for invalid tags, but it would be nice if it exposed something on the public API to sanitize tag values (perhaps simply removing all illegal characters)

**Comment by bretcope** [comment]
This would be super simple. Just need to provide a function which does a replace on the [InvalidChars](https://github.com/bretcope/BosunReporter.NET/blob/master/BosunReporter/Infrastructure/Validation.cs#L8) regex. Probably all of that `Validation` class could be moved and made public.

**Comment by bretcope** [comment]
I guess I forgot that there already is a `NameTransformers.Sanitize()` which converts all spans of invalid chars to a single underscore (or simply removes it if it's at the beginning or end of the string).

I'll probably keep that the way it is, and also make the invalid chars regex public so that people can write their own sanitize function if they want different functionality.

**Comment by bretcope** [comment]
I've made this change. The validation class is now named `BosunValidation`, and is public under the top namespace.

I also added a global tag value sanitize/normalize function option which you could use if you want the ability to apply a function to tag values across all metrics. See [BosunOptions.cs](https://github.com/bretcope/BosunReporter.NET/blob/master/BosunReporter/BosunOptions.cs#L58-L64).

**Comment by mgravell** [comment]
Awesome; thanks
