### ISSUE TITLE
Suggestion: automatic type conversion on tags

### ISSUE THREAD

**Issue by mgravell** [bretcope/BosunReporter.NET#20]
For example, this fails:

                [BosunTag]
                public readonly int Response;

but this works fine:

                [BosunTag]
                public readonly string Response;

It seems like the library could perform the string conversion itself?

**Comment by rossipedia** [comment]
+1 for this

**Comment by bretcope** [comment]
I can't allow arbitrary types because it's hard to enforce that the way values serialize won't change over time, which violates the strict immutability requirements the library enforces. It could work for primitives, but I'm hesitant to encourage people to use numeric types for tag values because I feel like it encourages an unbounded list of possible values.

However, what I really _do_ want to encourage people to use are enums. So I've added support for enum fields being marked with the `BosunTag` attribute.

You can now do this:

```csharp
    public enum SomeEnum
    {
        One = 1,
        Two = 2,
        Three = 3,
        Four = 4,
    }

    public class EnumCounter : Counter
    {
        [BosunTag] public readonly SomeEnum Value;

        public EnumCounter(SomeEnum val)
        {
            Value = val;
        }
    }
```

If you really want to use an int, there's nothing stopping you from calling `.ToString()` on it. I just don't want to _encourage_ using numbers without it giving you some pause. This seems like a fair compromise to me.
