### ISSUE TITLE
Metadata not being sent if MetricsCollector exists only for a short time

### ISSUE THREAD

**Issue by georgeduckett** [bretcope/BosunReporter.NET#30]
I have a small console app that gets triggered by windows after certain events. It's supposed to fire up, read a few files and record metrics, then close. It does minimal work and is active for a very short period of time.

What I've found is this means it doesn't reliably send meta data. I'm calling `Shutdown()` to ensure metrics are sent, but I couldn't find an equivalent for sending the meta data.

Is there something I'm missing?  
Should the meta data be sent from within the Shutdown method (if it wasn't previously sent)?  
Should a public method be made available to force sending meta data?

**Comment by bretcope** [comment]
That's an interesting use case I hadn't thought of before. The reason it doesn't immediately send metadata is that there are some metrics which aren't initialized when the app loads - they get created when requests start coming in. So, I delay the first metadata post by 30 seconds in the hopes that all metrics will have been created by then.

I don't like the idea of posting metadata during shutdown because I don't want to add extra work when the app is trying to shut down.

I think publicly exposing a method to post metadata is the right solution. It's really just a matter of making the existing [PostMetadata](https://github.com/bretcope/BosunReporter.NET/blob/master/BosunReporter/MetricsCollector.cs#L922) method public, and removing the junk parameter that is only there because it's used as a delegate for a timer. I should probably also make the initial reporting delay configurable. Right now it's hard coded to 30 seconds.

**Comment by georgeduckett** [comment]
Ok, that makes sense. The console app would've shut down within the first 30 seconds so that explains it.

No problem if you don't agree with my reasoning for posting metadata on shutdown, but my thinking is that there's already some work done in the shutdown method (posting a final snapshot), plus in the use case where the app is short-lived it seems inconsistent (to me) that metrics are ensured to be posted, but not the metadata about those metrics.

Like I say, no problem if you don't agree; I can see the counter arguments to the above.

Would making the changes either way be something you have time to do, or would you prefer a pull request when I've got a bit of free time?

**Comment by bretcope** [comment]
I plan to get to this tomorrow. It should be pretty simple, and I've got some other updates that have been waiting to be released too.

**Comment by bretcope** [comment]
I implemented what I said I would, but after giving it a little bit more thought, I think I'm going to revise it.

Here's the behavior I'm considering:

1. When a new metric is created, the MetricsCollector tracks that there is new metadata to send.
2. Metadata posting runs on the same schedule as metrics. Immediately after sending metrics to Bosun, metadata is re-posted if there is anything new to send. This would apply to shutdown as well.
3. Metadata is re-posted every 24 hours, even if nothing has changed. This is just to guard against having Bosun's metadata cleared for a long-running application.

I think that's an improvement for all use cases.

**Comment by bretcope** [comment]
This should finally be [resolved in 4.0.0](https://github.com/bretcope/BosunReporter.NET/blob/master/docs/ReleaseNotes.md), which was just released.
